DROP TABLE USERS;
DROP TABLE PERMISSIONS;
DROP TABLE GENDER;
DROP TABLE SEX;
DROP TABLE BLOOD_TYPE;
DROP TABLE USERS_PERMISSIONS;

DROP TABLE USERS_PERMISSIONS;
DROP TABLE USERS;

DROP TABLE STATE;
DROP TABLE COUNTRY;
DROP TABLE USERS;
