DROP TABLE ALLERGY_TREATMENT;
DROP TABLE USERS_ALLERGY;
DROP TABLE ALLERGY;
DROP TABLE ADMINISTERED;
DROP TABLE PRESCRIPTION;
DROP TABLE MEDICATION;
DROP TABLE ALERT;
DROP TABLE BMI;
DROP TABLE VITAL_SIGNS;
DROP TABLE USERS_CONTACT;
DROP TABLE USERS_ADDRESS;
DROP TABLE USERS_PERMISSIONS;
DROP TABLE DOCTOR;
DROP TABLE LOGIN;
DROP TABLE USERS

DROP TABLE MEDICATION_TYPE;
DROP TABLE UNIT_OF_MEASURE;
DROP TABLE SEVERITY;
DROP TABLE EFFECTIVENESS;
DROP TABLE FREQUENCY;
DROP TABLE ALLERGY_CATEGORY;
DROP TABLE GENDER;
DROP TABLE SEX;
DROP TABLE BLOOD_TYPE;
DROP TABLE STATE;
DROP TABLE COUNTRY;
DROP TABLE PERMISSIONS;



;
