INSERT INTO GENDER (gender_name) VALUES ('male');
INSERT INTO GENDER (gender_name) VALUES ('female');
INSERT INTO GENDER (gender_name) VALUES ('other');
INSERT INTO SEX (sex_name) VALUES ('male');
INSERT INTO SEX (sex_name) VALUES ('female');
INSERT INTO BLOOD_TYPE (blood_type_name) VALUES ('O+');
INSERT INTO BLOOD_TYPE (blood_type_name) VALUES ('O-');
INSERT INTO BLOOD_TYPE (blood_type_name) VALUES ('A+');
INSERT INTO BLOOD_TYPE (blood_type_name) VALUES ('A-');
INSERT INTO BLOOD_TYPE (blood_type_name) VALUES ('B+');
INSERT INTO BLOOD_TYPE (blood_type_name) VALUES ('B-');
INSERT INTO BLOOD_TYPE (blood_type_name) VALUES ('AB+');
INSERT INTO BLOOD_TYPE (blood_type_name) VALUES ('AB-');


INSERT INTO COUNTRY(country_name, country_code) VALUES("Afghanistan","AFG");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Albania","ALB");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Algeria","DZA");
INSERT INTO COUNTRY(country_name, country_code) VALUES("American Samoa","ASM");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Andorra","AND");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Angola","AGO");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Anguilla","AIA");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Antarctica","ATA");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Antigua and Barbuda","ATG");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Argentina","ARG");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Armenia","ARM");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Aruba","ABW");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Australia","AUS");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Austria","AUT");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Azerbaijan","AZE");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Bahamas","BHS");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Bahrain","BHR");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Bangladesh","BGD");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Barbados","BRB");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Belarus","BLR");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Belgium","BEL");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Belize","BLZ");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Benin","BEN");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Belize","BLZ");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Bermuda","BMU");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Bhutan","BTN");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Bolivia","BOL");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Bonaire","BES");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Bosnia and Herzegovina","BIH");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Botswana","BWA");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Bouvet Island","BVT");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Brazil","BRA");
INSERT INTO COUNTRY(country_name, country_code) VALUES("British Indian Ocean Territory","IOT");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Brunei Darussalam","BRN");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Bulgaria","BGR");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Burkina Faso","BFA");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Burundi","BDI");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Cabo Verde","CPV");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Cambodia","KHM");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Cameroon","CMR");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Canada","CAN");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Cayman Islands","CYM");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Central African Republic","CAF");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Chad","TCD");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Chile","CHL");
INSERT INTO COUNTRY(country_name, country_code) VALUES("China","CHN");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Christmas Island","CCK");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Cocos","CCK");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Colombia","COL");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Comoros","COM");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Congo","COG");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Cook Islands","COK");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Costa Rica","CRI");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Croatia","HRV");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Cuba","CUB");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Curaçao","CUW");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Cyprus","CYP");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Czechia","CZE");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Côte d'Ivoire","CIV");
INSERT INTO COUNTRY(country_name, country_code) VALUES("Denmark","DNK");


INSERT INTO STATE(state_name, state_code, country_id) VALUES("Queensland","QLD", 13);
INSERT INTO STATE(state_name, state_code, country_id) VALUES("New South Wales","NSW", 13);
INSERT INTO STATE(state_name, state_code, country_id) VALUES("Victoria","VIC", 13);
INSERT INTO STATE(state_name, state_code, country_id) VALUES("Western Australia","WA", 13);
INSERT INTO STATE(state_name, state_code, country_id) VALUES("South Australia","SA", 13);
INSERT INTO STATE(state_name, state_code, country_id) VALUES("Tasmania","TAS", 13);
INSERT INTO STATE(state_name, state_code, country_id) VALUES("Australian Capital Territory","ACT", 13);
INSERT INTO STATE(state_name, state_code, country_id) VALUES("Northern Territory","NT", 13);
