'use client'

// React Imports
import { useEffect, useState } from 'react'

// MUI Imports
import Grid from '@mui/material/Grid'
import Typography from '@mui/material/Typography'
import Box from '@mui/material/Box';
import LinearProgress from '@mui/material/LinearProgress';

// Third-party Imports
import { useSession } from 'next-auth/react'


const HomePageWrapper = () => {
  const [doFetch, setDoFetch] = useState(true);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [isVisible, setIsVisible] = useState(false);
  const { data: session, status } = useSession()

  useEffect(() => {
    const handleResize = () => {
      setIsVisible(window.innerWidth > 500);
    };

    // Set initial state
    handleResize();

    // Attach event listener
    window.addEventListener("resize", handleResize);

    // Cleanup listener on component unmount
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  
  async function fetchData(id) {
    try {
      const response = await fetch(`/api/pages/home?userId=${id}`);

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const json = await response.json();

      setResult(json);
    } catch (err) {
      setError(err.message);
    }
  }

  if (status === "authenticated" && doFetch) {
    fetchData(session.user.id);
    setDoFetch(false);
  }

  if (error) {
    return <div>Error: {error}</div>;
  }

  if (!result) {
    return (
      <Box sx={{ width: '100%' }}>
        <LinearProgress />
      </Box>
    );
  }
  

  return (
    <>
    <Grid container spacing={3}>
      <Grid item xs={isVisible ? 4 : false}></Grid>
      <Grid item xs={isVisible ? 4 : 12}>
        <Typography align='center' className='font-extrabold text-primary sm:text-[30px] text-3xl mbe-4 leading-[44px]'>
          Automatically Generated by AI
        </Typography>
        <Typography align='center' className='text-primary sm:text-[18px] text-3xl mbe-4 leading-[44px]'>
          (Please use with caution)
        </Typography>
      </Grid>
      <Grid item xs={isVisible ? 4 : false}></Grid>
    </Grid>
    <Grid container spacing={3}>
      <Grid item xs={isVisible ? 2 : false}></Grid>
      <Grid item xs={isVisible ? 8 : 12}>
        <Typography 
          sx={{ pt:4 }} 
          className='font-medium' 
          color='black'
          variant="p"
          >
          <div dangerouslySetInnerHTML={{ __html: result.message }} />
        </Typography>
      </Grid>
      <Grid item xs={ isVisible ? 2 : false}></Grid>
    </Grid>
    </>
  )
}

export default HomePageWrapper
